### ISSUE TITLE
Lines have the same distance

### ISSUE THREAD

**Issue by florianpircher** [tcarisland/GradientHatch#39]
Tested in the latest cutting edge version (3.2, 3041) and the normal release version (3.1.2):

<img width="1036" alt="Bildschirmfoto 2024-02-14 um 17 22 09" src="https://github.com/tcarisland/GradientHatch/assets/3776198/27ff565f-e24a-445b-a25c-51d7c277d690">

I get this error in the Macro Console on first run of the filter:

```
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 615, in process_
  File "plugin.py", line 212, in filter
    self.runFilter(layer, angle, offsetPath, [offsetPathStart, offsetPathEnd], stepWidth, [originX, originY], expandBeforeInset)
  File "plugin.py", line 222, in runFilter
    layer = hatchFilter.hatchLayerWithOrigin(layer, angle, offsetPathEnabled, strokeWidths, stepWidth, origin)
  File "gradienthatchfilter.py", line 27, in hatchLayerWithOrigin
    glyphHeight = hatchMetrics.getHeight()
  File "hatchmetrics.py", line 29, in getHeight
    return self.ascender + (self.descender * -1)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Comment by tcarisland** [comment]
![Skjermbilde 2024-02-14 kl  20 29 56](https://github.com/tcarisland/GradientHatch/assets/11506194/681ac074-ab6d-4f74-872d-d0412d97ce42)

Managed to reproduce the error, I think I ended up making some language-sensitive code by relying on the title for the metric. I should find a way to get the Ascender and Descender without using the title-field

`
    @objc.python_method
    def getMetricFromLayer(self, layer, metricName):
        try:
            for metricValueName in layer.master.metricValues:
                if layer.master.metricValues[metricValueName].title() == metricName:
                    return int(layer.master.metricValues[metricValueName].position)
        except TypeError:
            for metricValue in layer.master.metrics:
                if metricValue.title() == metricName:
                    return int(metricValue.position)

    @objc.python_method
    def setGlyphHeightFromLayer(self, layer):
        self.ascender = self.getMetricFromLayer(layer, 'Ascender')
        self.descender = self.getMetricFromLayer(layer, 'Descender')
`

**Comment by florianpircher** [comment]
You can use those value as properties on the layer directly:

https://docu.glyphsapp.com/#GSLayer.ascender

```
x = layer.ascender
y = layer.descender
```

**Comment by tcarisland** [comment]
Thanks, I'll do that as a refactoring job.

I also noticed that there's an enum in the GSMetric-field of the GSMetricValue, I used this to fix the problem and tested on the latest Glyphs version and the normal release version.

**Comment by tcarisland** [comment]
I still have the infinite loop bug to fix, it should be fairly straightforward to add constraints to the setter method or in the GUI.

I'll just remove the localisation for simplicity and look into auto-layout later.

**Comment by florianpircher** [comment]
OK, write a comment on the pull request when you think you are ready and feel free to ask if you have any questions along the way.
