### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by florianpircher** [tcarisland/GradientHatch#41]
Some of the automatic string translations can be confusing. At least for German I will have a look and send you an updated list when I get time.

Similarly, the layout does not change for strings of different lengths, which causes some labels to clip. I f you want to, I can have a look at setting up Auto Layout to handle that.

**Comment by tcarisland** [comment]
Thanks, the IBdialog.strings are generated from this yml-file, I'll remove all the auto-translated ones and open for suggestions in the forum or similar.

https://github.com/tcarisland/tclang/blob/main/src/main/resources/projects/advancedhatch/advancedhatch_translated.yml
